name: gaman
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
repository: https://github.com/hubble459/gaman

environment:
  sdk: ^3.2.6

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  freezed_annotation: ^2.4.1
  gio: ^0.0.4
  html: ^0.15.4
  jiffy: ^6.2.2
  json_annotation: ^4.8.1
  pseudom:
    # WIP
    path: '../pseudom'

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
  yaml: ^3.1.2
