name: gaman
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  gio: ^0.0.4
  html: ^0.15.4
  jiffy: ^6.2.2
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
  yaml: ^3.1.2
